// Generated by timeline-ui/scripts/sync-themes.mjs — do not edit manually.

import Foundation

enum WebColorTheme: String, CaseIterable {
    case catppuccin
    case dracula
    case everforest
    case gruvbox
    case ledger
    case nord
    case oneDark = "one-dark"
    case rosePine = "rose-pine"
    case slate
    case solarized
    case tokyoNight = "tokyo-night"
}

extension WebColorTheme {
    /// 主题子菜单英文标题（由文件名推导；不本地化）。
    var menuTitleEnglish: String {
        switch self {
        case .catppuccin: return "Catppuccin"
        case .dracula: return "Dracula"
        case .everforest: return "Everforest"
        case .gruvbox: return "Gruvbox"
        case .ledger: return "Ledger"
        case .nord: return "Nord"
        case .oneDark: return "One Dark"
        case .rosePine: return "Rose Pine"
        case .slate: return "Slate"
        case .solarized: return "Solarized"
        case .tokyoNight: return "Tokyo Night"
        }
    }
}
