/**
 * 扫描 `src/styles/themes/*.css`，生成：
 * - `src/lib/ccTheme.generated.ts`（CC_THEME_IDS）
 * - `src/styles/cc-theme-colors.css`（@import 列表）
 * - `../CCReader/Services/WebColorTheme.generated.swift`（枚举 + 菜单英文标题）
 * - 四处 HTML 内联 `var ok = { ... }` 白名单
 *
 * 用法：在 `timeline-ui` 目录执行 `node scripts/sync-themes.mjs`
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const timelineRoot = path.join(__dirname, '..');
const repoRoot = path.join(timelineRoot, '..');

const DEFAULT_THEME_ID = 'everforest';

const themesDir = path.join(timelineRoot, 'src/styles/themes');
const files = fs
  .readdirSync(themesDir)
  .filter((f) => f.endsWith('.css'))
  .map((f) => f.replace(/\.css$/, ''))
  .sort((a, b) => a.localeCompare(b, 'en'));

if (files.length === 0) {
  console.error('sync-themes: no .css files in', themesDir);
  process.exit(1);
}
if (!files.includes(DEFAULT_THEME_ID)) {
  console.error(
    `sync-themes: default theme "${DEFAULT_THEME_ID}" has no themes/${DEFAULT_THEME_ID}.css — fix or change DEFAULT_THEME_ID in scripts/sync-themes.mjs and ccTheme.ts`
  );
  process.exit(1);
}

function idToSwiftCaseName(id) {
  const parts = id.split('-');
  if (parts.length === 1) return parts[0];
  return parts[0] + parts.slice(1).map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('');
}

function idToMenuTitle(id) {
  return id
    .split('-')
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join(' ');
}

// ---- TypeScript ----
const tsOut = path.join(timelineRoot, 'src/lib/ccTheme.generated.ts');
const tsBody = `/**
 * Generated by scripts/sync-themes.mjs — do not edit manually.
 */

export const CC_THEME_IDS = [
${files.map((id) => `  '${id}',`).join('\n')}
] as const;
`;
fs.writeFileSync(tsOut, tsBody, 'utf8');
console.log('wrote', path.relative(repoRoot, tsOut));

// ---- cc-theme-colors.css ----
const cssOut = path.join(timelineRoot, 'src/styles/cc-theme-colors.css');
const cssBody = `/**
 * CCReader 颜色主题入口：每个主题单独文件，见 \`themes/\`。
 * 灵感来自各开源配色方案（Nord、Dracula、Catppuccin 等），已映射到本项目的语义 token。
 *
 * 下方 @import 由 scripts/sync-themes.mjs 根据 themes/*.css 生成，请勿手改列表。
 */

${files.map((id) => `@import './themes/${id}.css';`).join('\n')}
`;
fs.writeFileSync(cssOut, cssBody, 'utf8');
console.log('wrote', path.relative(repoRoot, cssOut));

// ---- Swift ----
const swiftOut = path.join(repoRoot, 'CCReader/Services/WebColorTheme.generated.swift');
const swiftCases = files
  .map((id) => {
    const name = idToSwiftCaseName(id);
    if (id === name) return `    case ${id}`;
    return `    case ${name} = "${id}"`;
  })
  .join('\n');

const swiftMenuSwitch = files
  .map((id) => {
    const caseName = idToSwiftCaseName(id);
    const title = idToMenuTitle(id).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
    return `        case .${caseName}: return "${title}"`;
  })
  .join('\n');

const swiftBody = `// Generated by timeline-ui/scripts/sync-themes.mjs — do not edit manually.

import Foundation

enum WebColorTheme: String, CaseIterable {
${swiftCases}
}

extension WebColorTheme {
    /// 主题子菜单英文标题（由文件名推导；不本地化）。
    var menuTitleEnglish: String {
        switch self {
${swiftMenuSwitch}
        }
    }
}
`;
fs.writeFileSync(swiftOut, swiftBody, 'utf8');
console.log('wrote', path.relative(repoRoot, swiftOut));

// ---- HTML whitelist ----
const htmlOkRe = /var ok = \{[\s\S]*?\};/m;

function patchHtmlOk(html) {
  const lines = files.map((id) => {
    const key = /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(id) ? id : `'${id}'`;
    return `            ${key}: 1,`;
  });
  const block = `var ok = {\n${lines.join('\n')}\n          };`;
  if (!htmlOkRe.test(html)) {
    throw new Error('sync-themes: could not find var ok = { ... }; in HTML');
  }
  return html.replace(htmlOkRe, block);
}

const htmlPaths = [
  path.join(timelineRoot, 'public/timeline-shell.html'),
  path.join(timelineRoot, 'public/markdown-preview.html'),
  path.join(repoRoot, 'CCReader/Resources/timeline-shell.html'),
  path.join(repoRoot, 'CCReader/Resources/markdown-preview.html'),
];

for (const p of htmlPaths) {
  const before = fs.readFileSync(p, 'utf8');
  fs.writeFileSync(p, patchHtmlOk(before), 'utf8');
  console.log('patched', path.relative(repoRoot, p));
}

console.log('sync-themes: ok,', files.length, 'themes.');
