/**
 * Generated by scripts/sync-themes.mjs — do not edit manually.
 */

export const CC_THEME_IDS = [
  'catppuccin',
  'dracula',
  'everforest',
  'gruvbox',
  'ledger',
  'nord',
  'one-dark',
  'rose-pine',
  'slate',
  'solarized',
  'tokyo-night',
] as const;
